#!/bin/bash

[ -z $ESHOP_FACTS ] && echo "Please run this script through oe-eshop-facts, e.g. ./oe-eshop-facts $0" && exit 1
. $ESHOP_FACT_BIN_PATH
. "$(dirname $BASH_SOURCE)/oe-eshop-db_migration_facts"

function main {
    check_preconditions
    generate_migration
}

function check_preconditions {
    [ -z "$MIGRATION_SUITE" ] \
        && echo "Environment variable \"MIGRATION_SUITE\" is not specified. Please provide the mentioned environment variable and run the script." \
        && exit 1
}

function generate_migration {
    local CMD=":generate -n"

    [ -f $ESHOP_DOCTRINE_MIGRATION_WRAPPER_BIN_PATH ] && $ESHOP_DOCTRINE_MIGRATION_WRAPPER_BIN_PATH "$CMD"
}

main

exit 0
